# Generated by Django 3.2.16 on 2022-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studcamp', '0002_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='cpassword',
            field=models.CharField(max_length=15),
        ),
    ]
