# Generated by Django 3.2.16 on 2022-11-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studcamp', '0003_alter_signup_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('cname', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
