# Generated by Django 3.2.16 on 2022-11-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studcamp', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=250)),
                ('sname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=15)),
                ('salary', models.CharField(max_length=15)),
            ],
        ),
    ]
