# Generated by Django 3.2.16 on 2022-11-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studcamp', '0006_alter_staff_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sname', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=15)),
            ],
        ),
    ]
