# Generated by Django 3.2.16 on 2022-11-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studcamp', '0007_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sname',
        ),
    ]
