# Generated by Django 3.2.16 on 2022-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studcamp', '0008_auto_20221103_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('shr', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=600)),
            ],
        ),
    ]
